import { useEffect, useMemo, useState } from "react";
import { FaWallet, FaClock, FaExclamationCircle, FaReceipt } from "react-icons/fa";
import toast from "react-hot-toast";
import { StatCard } from "../../components/ui/Card";
import Badge from "../../components/ui/Badge";
import InvoiceModal from "../../components/modals/InvoiceModal";
import { getInvoices } from "../../services/billingService";

const statusVariant = { PAID: "success", Paid: "success", PENDING: "warning", Pending: "warning", OVERDUE: "danger", Overdue: "danger", CANCELLED: "danger" };
export default function Billing() {
  const [invoices,setInvoices]=useState([]); const [active,setActive]=useState(null); const [loading,setLoading]=useState(true);
  const load=async()=>{try{setLoading(true);const d=await getInvoices();setInvoices(Array.isArray(d)?d:[]);}catch(e){toast.error(e?.response?.data?.message||"Could not load invoices");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const stats=useMemo(()=>{const collected=invoices.reduce((s,i)=>s+Number(i.paidAmount||0),0);const pending=invoices.reduce((s,i)=>s+Math.max(Number(i.dueAmount||0),0),0);const overdue=invoices.filter(i=>String(i.status).toUpperCase()==="OVERDUE").reduce((s,i)=>s+Number(i.dueAmount||0),0);const avg=invoices.length?Math.round(invoices.reduce((s,i)=>s+Number(i.totalAmount||0),0)/invoices.length):0;return{collected,pending,overdue,avg};},[invoices]);
  const exportCsv=()=>{const rows=[["Invoice","Patient","Total","Paid","Due","Status","Payment status"],...invoices.map(i=>[i.invoiceNumber,i.patientId,i.totalAmount,i.paidAmount,i.dueAmount,i.status,i.paymentStatus])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="zenve-invoices.csv";a.click();URL.revokeObjectURL(url);};
  if(loading)return <div className="table-card"><div className="table-empty">Loading invoices...</div></div>;
  return <div className="stack-6"><div className="stat-grid"><StatCard icon={FaWallet} label="Collected" value={`₹${stats.collected.toLocaleString("en-IN")}`} iconBg="success"/><StatCard icon={FaClock} label="Pending" value={`₹${stats.pending.toLocaleString("en-IN")}`} iconBg="warning"/><StatCard icon={FaExclamationCircle} label="Overdue" value={`₹${stats.overdue.toLocaleString("en-IN")}`} iconBg="danger"/><StatCard icon={FaReceipt} label="Avg. ticket" value={`₹${stats.avg.toLocaleString("en-IN")}`} iconBg="info"/></div><div className="table-card"><table><thead><tr><th>Invoice</th><th>Patient</th><th>Total</th><th>Paid</th><th>Due</th><th>Status</th><th /></tr></thead><tbody>{invoices.map(i=><tr key={i.id} onClick={()=>setActive(i)} style={{cursor:"pointer"}}><td><p className="cell-title">{i.invoiceNumber||`INV-${i.id}`}</p><p className="cell-sub">{i.invoiceDate||"—"}</p></td><td><p className="cell-title">Patient #{i.patientId||"—"}</p><p className="cell-sub">Owner #{i.ownerId||"—"}</p></td><td className="cell-title">₹{Number(i.totalAmount||0).toLocaleString("en-IN")}</td><td className="text-muted">₹{Number(i.paidAmount||0).toLocaleString("en-IN")}</td><td className="text-muted">₹{Number(i.dueAmount||0).toLocaleString("en-IN")}</td><td><Badge variant={statusVariant[i.paymentStatus]||statusVariant[i.status]||"slate"}>{i.paymentStatus||i.status||"—"}</Badge></td><td style={{textAlign:"right"}}>›</td></tr>)}{!invoices.length&&<tr><td colSpan={7} className="table-empty">No invoices in the backend.</td></tr>}</tbody></table></div><div style={{display:"flex",justifyContent:"flex-end"}}><button className="link-btn" onClick={exportCsv}>Export GST report</button></div><InvoiceModal open={!!active} invoice={active} onClose={()=>setActive(null)} onUpdated={load}/></div>;
}
